datasets:
  vast27M:
    data_type: video
    build_info:
      anno_dir: /mnt/disks/chfuab/video-llama/data/vast27m/train/annotations
      videos_dir: /mnt/disks/chfuab/video-llama/data/vast27m/train/videos
      anno_dir_val: /mnt/disks/chfuab/video-llama/data/vast27m/eval/annotations
      videos_dir_val: /mnt/disks/chfuab/video-llama/data/vast27m/eval/videos
