datasets:
  nextQA:
    data_type: video
    build_info:
      anno_dir: /mnt/disks/chfuab/nextqa/anno_dir_train/
      videos_dir: /mnt/disks/chfuab/nextqa/videos_dir_train/
      anno_dir_val: /mnt/disks/chfuab/nextqa/anno_dir_val/
      videos_dir_val: /mnt/disks/chfuab/nextqa/videos_dir_val/